In [7]:
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l


def f(x):
    return 3 * x ** 2 - 4 * x

In [8]:
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [3]:
import torch
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [4]:
x.grad

In [5]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [9]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [18]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [28]:
x.grad.zero_()
y = x * x
y.mean().backward()
x.grad

tensor([0.0000, 0.5000, 1.0000, 1.5000])

In [48]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a, d, a.grad, d / a


(tensor(-0.0670, requires_grad=True),
 tensor(-109738.6484, grad_fn=<MulBackward0>),
 tensor(1638400.),
 tensor(1638400., grad_fn=<DivBackward0>))