In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return x - x.mean()

In [4]:
layer = CenteredLayer()
x = torch.FloatTensor([1, 2, 3, 4, 5])
layer(x), x.mean()

(tensor([-2., -1.,  0.,  1.,  2.]), tensor(3.))

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [6]:
y = net(torch.rand(4, 8))
y.mean()

tensor(2.7940e-09, grad_fn=<MeanBackward0>)

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.5640, -0.8073, -0.0951],
        [-0.2051, -0.4351, -0.2521],
        [-1.0288,  1.5723,  0.8566],
        [ 0.8896,  1.4969,  0.4553],
        [-1.0980, -0.2216,  0.9687]], requires_grad=True)

In [10]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.7198, 0.1770],
        [0.0000, 1.5085, 0.0098]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 8.3081],
        [12.5735]])